version: '3'

includes:
  common: ./build/Taskfile.common.yml
  windows: ./build/Taskfile.windows.yml
  darwin: ./build/Taskfile.darwin.yml
  linux: ./build/Taskfile.linux.yml

vars:
  APP_NAME: "wayd"
  BIN_DIR: "bin"
  WAILS_VITE_PORT: '9347'
  VITE_PORT: '{{.WAILS_VITE_PORT | default 9246}}'
  # VITE_PORT: '9246'

tasks:

  build:
    summary: Builds the application
    cmds:
      - task: "{{OS}}:build"

  package:
    summary: Packages a production build of the application
    cmds:
      - cmd: rm -f ./bin/wayd
      - cmd: rm -rf ./bin/wayd.app
      - task: "{{OS}}:package"

  run:
    summary: Runs the application
    cmds:
      - task: "{{OS}}:run"

  dev:
    summary: Runs the application in development mode
    cmds:
      - wails3 dev -config ./build/devmode.config.yaml -port {{.VITE_PORT}}
