// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as appdirs$0 from "../../github.com/markgemmill/appdirs/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DatabasePath(): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByName("wayd/services.SettingsService.DatabasePath") as any;
    return $resultPromise;
}

export function GetSettings(): Promise<$models.Settings | null> & { cancel(): void } {
    let $resultPromise = $Call.ByName("wayd/services.SettingsService.GetSettings") as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function Initialize(appDirs: appdirs$0.AppDirs): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByName("wayd/services.SettingsService.Initialize", appDirs) as any;
    return $resultPromise;
}

export function Load(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByName("wayd/services.SettingsService.Load") as any;
    return $resultPromise;
}

export function Name(): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByName("wayd/services.SettingsService.Name") as any;
    return $resultPromise;
}

export function SetSettings(settings: $models.Settings | null): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByName("wayd/services.SettingsService.SetSettings", settings) as any;
    return $resultPromise;
}

export function Write(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByName("wayd/services.SettingsService.Write") as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = $models.Settings.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
