// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class AppDirs {
    "Name": string;
    "Version": string;

    /** Creates a new AppDirs instance. */
    constructor($$source: Partial<AppDirs> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Version" in $$source)) {
            this["Version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppDirs instance from a string or object.
     */
    static createFrom($$source: any = {}): AppDirs {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppDirs($$parsedSource as Partial<AppDirs>);
    }
}
