// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as slog$0 from "../../../../log/slog/models.js";

export function Debug(message: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2525972076, message) as any;
    return $resultPromise;
}

export function Logger(): Promise<slog$0.Logger | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4068771833) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

// Private type creation functions
const $$createType0 = slog$0.Logger.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
