// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as toml$0 from "../../../pelletier/go-toml/v2/models.js";

export class Settings {
    "PromptEvery": number;
    "DockPosition": string;
    "PromptCycle": number;
    "SyncCycleTo": string;
    "DayStartsAt": toml$0.LocalTime;
    "DayEndsAt": toml$0.LocalTime;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("PromptEvery" in $$source)) {
            this["PromptEvery"] = 0;
        }
        if (!("DockPosition" in $$source)) {
            this["DockPosition"] = "";
        }
        if (!("PromptCycle" in $$source)) {
            this["PromptCycle"] = 0;
        }
        if (!("SyncCycleTo" in $$source)) {
            this["SyncCycleTo"] = "";
        }
        if (!("DayStartsAt" in $$source)) {
            this["DayStartsAt"] = "";
        }
        if (!("DayEndsAt" in $$source)) {
            this["DayEndsAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings($$parsedSource as Partial<Settings>);
    }
}
